version: "3.3"
services:
  iNoi:
    restart: always
    volumes:
      - "/etc/inoi:/opt/inoi/data"
    ports:
      - "5244:5244"
      - "5245:5245"
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=UTC
    container_name: inoi
    image: "leolitaly/inoi:latest"
